version: '3.8'

services:
  backend:
    build:
      context: ./firewall-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./firewall-app:/app
      - ./absolution:/app/absolution
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - vessa-network

  frontend:
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./www:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run dev
    networks:
      - vessa-network
    depends_on:
      - backend

networks:
  vessa-network:
    driver: bridge 