"""Add audit log table

Revision ID: 24fcff65dfc3
Revises: cbea353d4a0b
Create Date: 2025-10-28 00:14:09.329563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fcff65dfc3'
down_revision = 'cbea353d4a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
