"""Initial migration

Revision ID: cbea353d4a0b
Revises: 
Create Date: 2025-10-28 00:10:02.621378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbea353d4a0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responseaction')
    op.drop_table('malicious_request')
    op.drop_table('incidentresponse')
    op.drop_table('notification')
    op.drop_table('incidentattachment')
    op.drop_table('incident')
    op.drop_table('notification_preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('channel', mysql.ENUM('EMAIL', 'WEBSOCKET', 'WEBHOOK'), nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('min_priority', mysql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), nullable=True),
    sa.Column('webhook_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_preference_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('incident',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('severity', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('detection_source', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('affected_assets', mysql.JSON(), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('resolved_at', mysql.DATETIME(), nullable=True),
    sa.Column('resolution_notes', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('threat_details', mysql.JSON(), nullable=True),
    sa.Column('mitigation_steps', mysql.JSON(), nullable=True),
    sa.Column('false_positive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('reporter_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('assigned_to', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('closed_at', mysql.DATETIME(), nullable=True),
    sa.Column('priority_score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name='incident_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], name='incident_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('incidentattachment',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('incident_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_path', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('uploader_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name='incidentattachment_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], name='incidentattachment_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notification',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('priority', mysql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('incident_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('read_at', mysql.DATETIME(), nullable=True),
    sa.Column('delivered_channels', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name='notification_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('incidentresponse',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('incident_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('responder_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('response_priority', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=False),
    sa.Column('resolved_at', mysql.DATETIME(), nullable=True),
    sa.Column('resolution_summary', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('time_to_respond', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_to_resolve', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name='incidentresponse_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['user.id'], name='incidentresponse_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('malicious_request',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('source_ip', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('request_path', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('request_method', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('threat_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('threat_score', mysql.FLOAT(), nullable=False),
    sa.Column('headers', mysql.JSON(), nullable=True),
    sa.Column('body', mysql.JSON(), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('is_blocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('incident_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('api_key_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('threat_details', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], name='malicious_request_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name='malicious_request_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('responseaction',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('response_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('action_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('performed_by', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('performed_at', mysql.DATETIME(), nullable=False),
    sa.Column('result', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('artifacts', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], name='responseaction_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['incidentresponse.id'], name='responseaction_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
